
<div id="homePagePicker" style="width: 470px;height: 300px;">
	<div class="home-page-head">
		I am,
	</div>
	<div  class="home-page-images">		
		
		<img  id="forTheNotion" src="/graphics/for-front-page.jpg" border="0" />
		
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				
		<img id="againstTheNotion"  src="/graphics/against-front-page.jpg" border="0" />
		
	</div>
	<div class="home-page-head">
		the Notion
	</div>

	<div class="home-page-head">
		&nbsp;
	</div>
	
	<div class="home-page-subtitle">
		Undecided? Don't care? Just here to read?
	</div>
	
	<div class="home-page-head">
		&nbsp;
	</div>	
</div>
<div id="homePage" style="width: 470px;height: 300px;display: none;">
</div>
<div id="main_message_block" style="clear: both; height: 170px;overflow: hidden;">
	<?php foreach ($this->responses as $response):?>
		<div class="<?php echo $this->responseType[$response->type] ?>Message">
			<?php echo $response->message ?>
			<div class="message_metadata">posted: <?php echo date("M d, y h:i a",strtotime($response->date_created)) ?> (User <?php echo $response->user ?>)</div>			
		</div>
	<?php endforeach;?>
</div>

<input type="hidden" value="<?php echo $this->responses[0]->id?>" id="last_message" />
                    
<script language="javascript">
	
	//<![CDATA[
	$(document).ready(
		function()
		{	
			var x = window.setInterval("getMessages('<?php echo $this->baseUrl;?>/index/getmessages/debate/<?php echo $this->debate->id?>/last_message/' + document.getElementById('last_message').value );", 15000);
			countdown(9215,'countdown_label');
		
			$("#forTheNotion").click(function () {
				$("#homePagePicker").hide();
				$("#homePage").load("/user/login/decision/1")
								.hide()
								.fadeIn(1000);
				
			});
			
			$("#againstTheNotion").click(function () {
				$("#homePagePicker").hide();
				$("#homePage").load("/user/login/decision/2")
								.hide()
								.fadeIn(1000);
			});
			
			$("#loadSignupForm").click(function(){
				$("#homePageLogin").load("/user/signup");
			});
		}
	);
	//]]
</script>