<?php
/**
* @author Kshitij Bedi
* @copyright Zuova.com
* @version 1.0
* @package Layouts
*/
?>
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <?php echo $this->headTitle("Zuova.com") ?>    
    
    <?php echo $this->headScript()->appendFile('/jquery/jquery.form.js')
    							  ->appendFile('/jquery/jquery-ui.min.js')
    							  ->appendFile('/application.js');?>         
	<?php echo $this->headLink()->appendStylesheet('/application.css')
    							->appendStylesheet('/jquery/jquery-ui.css')  
    							->appendStylesheet('/jquery/smoothness/jquery-ui-1.7.2.custom.css');?>    
</head>

<body marginwidth=0 marginheight=0 style="margin: 1px;">

	<table height="100%" border="0" cellspacing="0" cellpadding="0" align="center" id="maintable">
		<tr>
			<td align="center" colspan="2" id="banner">		
				<?php echo $this->debate->question ?>	

				<div class="" style="float: center;width: 100px;padding: 10px 0px 0px 0px; vertical-align: bottom;font: normal 11px tahoma;color: #A8D63A;"><?=date("F j, Y")?></div>
			</td>
		</tr>
	    <tr>
			<td id="content" valign="top">
				<?php echo $this->layout()->content; ?>
			</td>    
			<!-- right navigation cell -->
			<td valign="top" id="nav" >
				<?php echo $this->render('nav.phtml') ?>
			</td>
		</tr>
			<td  colspan="2" valign="bottom" id="footer">			
			<img src="<?php echo Zend_Controller_Front::getInstance()->getRequest()->getBaseUrl();?>/graphics/site-logo.png"/> 
			- new day, new debate, new arguments, new resolutions, new opinions...
			</td>
		</tr>
	</table>
</body>
</html>
